// Supabase Configuration
// This file is automatically generated when connecting to Supabase project
// Project ID: glyroyxaohnuuugpumio

class SupabaseConfig {
  static const String supabaseUrl = 'https://glyroyxaohnuuugpumio.supabase.co';
  static const String supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdseXJveXhhb2hudXV1Z3B1bWlvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA4ODA1NTksImV4cCI6MjA4NjQ1NjU1OX0.yzf30x29WBcY5tCDQ3Df2UUAamIoAy9cdsPb6ubst48';
}
